version: '3.8'
services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cdbs
      MYSQL_USER: cdbuser
      MYSQL_PASSWORD: cdbpass sword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORS: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

  volumes:
    db_data:
